# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  pyright = nodeEnv.buildNodePackage {
    name = "pyright";
    packageName = "pyright";
    version = "1.1.121";
    src = fetchurl {
      url = "https://registry.npmjs.org/pyright/-/pyright-1.1.121.tgz";
      sha512 = "jb0BwO3nbiF808SDMpT4UXg30ats+8nsHyu4zTlSt1p4ZWl6+GNP98peDQyOYzgnoScTMomDYTDXejAAD3M+WA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Type checker for the Python language";
      homepage = "https://github.com/Microsoft/pyright#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}