# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  flake8-black = {
    pname = "flake8-black";
    version = "0.3.6";
    src = fetchurl {
      url = "https://pypi.io/packages/source/f/flake8-black/flake8-black-0.3.6.tar.gz";
      sha256 = "sha256-DfvKMnR3d5KlvLKviHpMrXLHLQ6GyU4I46PeFRu0HDQ=";
    };
  };
  flake8-deprecated = {
    pname = "flake8-deprecated";
    version = "2.0.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/f/flake8-deprecated/flake8-deprecated-2.0.1.tar.gz";
      sha256 = "sha256-x2WaUwqnbDrYvgwegzHtVtiC74v7oHRQGlRbszUrDCM=";
    };
  };
  flake8-isort = {
    pname = "flake8-isort";
    version = "6.0.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/f/flake8-isort/flake8-isort-6.0.0.tar.gz";
      sha256 = "sha256-U39FOmYNfpA/YC7Po2E2sUDeJ531jQLrG2oMhOg8Uow=";
    };
  };
}
