# This file has been generated by node2nix 1.9.0. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {};
in {
  pyright = nodeEnv.buildNodePackage {
    name = "pyright";
    packageName = "pyright";
    version = "1.1.155";
    src = fetchurl {
      url = "https://registry.npmjs.org/pyright/-/pyright-1.1.155.tgz";
      sha512 = "y7VqgiOMiLqzFzQ6LCVUtyb8VCsVbwzOHw16A5YxidGmARRYvFn1kIf1uCDqj3ytxrOcVHyptq90/TSffU0hZg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Type checker for the Python language";
      homepage = "https://github.com/Microsoft/pyright#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
