# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  pyright = nodeEnv.buildNodePackage {
    name = "pyright";
    packageName = "pyright";
    version = "1.1.298";
    src = fetchurl {
      url = "https://registry.npmjs.org/pyright/-/pyright-1.1.298.tgz";
      sha512 = "lDTIS0a7SJ6TCcACjPl1eXatYbctTgGd/Ji3aZ9oCJTVjZCIpwf4Huj6sSlhC3KmsHFCcLt4t1uFi0z/jm7qYg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Type checker for the Python language";
      homepage = "https://github.com/Microsoft/pyright#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
