# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  pyright = nodeEnv.buildNodePackage {
    name = "pyright";
    packageName = "pyright";
    version = "1.1.123";
    src = fetchurl {
      url = "https://registry.npmjs.org/pyright/-/pyright-1.1.123.tgz";
      sha512 = "EYjELbm4G4icuIki6PfpzYrxNeGH78vNbXNmsbb/9XnnVQISdFcbc9oOBc2mU77enUwZctwZ6Nj2mZUMD9VibQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Type checker for the Python language";
      homepage = "https://github.com/Microsoft/pyright#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
